/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mine.glb -T 
Files: mine.glb [11.61MB] > C:\Users\20155\Downloads\studying\Dev-Portfolio\Dev-Portfolio\public\models\mine-transformed.glb [1.13MB] (90%)
*/

import React, { useEffect, useRef } from "react";
import { useGraph } from "@react-three/fiber";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function ContactBoy(props) {
  const groupRef = useRef();
  const { scene } = useGLTF("/models/mine-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { animations } = useFBX("/models/Wave Hip Hop Dance.fbx");
  animations[0].name = "Dance";
  const action = useAnimations(animations, groupRef);
  useEffect(() => {
    action.actions["Dance"].play();
  }, [action]);
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name='Wolf3D_Avatar'
        geometry={nodes.Wolf3D_Avatar.geometry}
        material={materials.Wolf3D_Avatar}
        skeleton={nodes.Wolf3D_Avatar.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Avatar.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Avatar.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/mine-transformed.glb");
